Vagrant.configure("2") do |config|

  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.box_check_update = false
  config.disksize.size = "512GB"
  config.notify.enable = true
  config.vm.define "testing"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/akimdi/wiki/master/vagrant-php.sh"

  # Run Ansible from the Vagrant Host
  #
  # config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "playbook.yml"
  # end

  config.vm.provider "virtualbox" do |v|
   v.name = "php"
   v.gui = false
   v.memory = "2048"
   v.cpus = 2
   v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

end